### ISSUE TITLE
Не работает для Golang

### ISSUE THREAD

**Issue by DeOne4eg** [yandex-market/yandex-market-partner-api#1]
После генерации получается конфликт имен структур для разных моделей работы (FBS, FBY, DBS)

> ./api_dbs.go:1413:6: ApiDeleteOffersRequest redeclared in this block
        ./api_business_offer_mappings.go:26:6: other declaration of ApiDeleteOffersRequest
./api_dbs.go:2766:6: ApiGetCampaignRequest redeclared in this block
        ./api_campaigns.go:26:6: other declaration of ApiGetCampaignRequest
./api_dbs.go:3138:6: ApiGetCampaignLoginsRequest redeclared in this block
        ./api_campaigns.go:197:6: other declaration of ApiGetCampaignLoginsRequest
./api_dbs.go:3724:6: ApiGetCampaignRegionRequest redeclared in this block
        ./api_campaigns.go:368:6: other declaration of ApiGetCampaignRegionRequest
./api_dbs.go:3895:6: ApiGetCampaignSettingsRequest redeclared in this block
        ./api_campaigns.go:539:6: other declaration of ApiGetCampaignSettingsRequest
./api_dbs.go:4066:6: ApiGetCampaignsRequest redeclared in this block
        ./api_campaigns.go:710:6: other declaration of ApiGetCampaignsRequest
./api_dbs.go:4253:6: ApiGetCampaignsByLoginRequest redeclared in this block
        ./api_campaigns.go:897:6: other declaration of ApiGetCampaignsByLoginRequest
./api_dbs.go:6715:6: ApiGetOfferMappingsRequest redeclared in this block
        ./api_business_offer_mappings.go:220:6: other declaration of ApiGetOfferMappingsRequest
./api_dbs.go:9867:6: ApiGetSuggestedOfferMappingsRequest redeclared in this block
        ./api_business_offer_mappings.go:427:6: other declaration of ApiGetSuggestedOfferMappingsRequest
./api_dbs.go:10464:6: ApiPutBidsForBusinessRequest redeclared in this block
        ./api_bids.go:26:6: other declaration of ApiPutBidsForBusinessRequest
./api_dbs.go:10464:6: too many errors

**Comment by vbauer** [comment]
@DeOne4eg Можно пожалуйста добавить немного больше информации как запускался генератор / с какими параметрами / какая версия генератора использовалась и тп?

**Comment by DeOne4eg** [comment]
`go version go1.20.5 darwin/arm64`

`openapi-generator generate -i ../yandex-market-partner-openapi/openapi/openapi.yaml -packageName=yamarket -g go -o .`
> openapi-generator version
> 6.6.0

**Comment by MarketLLC** [comment]
@DeOne4eg Спасибо за информацию. Если правильно понимаю, то это известная проблема в генераторе для golang: https://github.com/OpenAPITools/openapi-generator/issues/741 При включении structPrefix=true и enumClassPrefix=true проблемы с redeclaration уходят

Но кажется это не единственная проблема генератора и возникает другой сбой:
```
./api_bids.go:30:8: undefined: BusinessesBusinessIdBids
./api_bids.go:237:8: undefined: CampaignsCampaignIdBids
./api_business_offer_mappings.go:30:8: undefined: BusinessesBusinessIdOfferMappingsDelete
./api_business_offer_mappings.go:224:8: undefined: BusinessesBusinessIdOfferMappings
./api_business_offer_mappings.go:431:8: undefined: BusinessesBusinessIdOfferMappingsSuggestions
./api_business_offer_mappings.go:637:8: undefined: BusinessesBusinessIdOfferMappingsUpdate
./api_dbs.go:33:8: undefined: CampaignsCampaignIdOrdersOrderIdCancellationAccept
./api_dbs.go:224:8: undefined: CampaignsCampaignIdHiddenOffers
./api_dbs.go:423:8: undefined: BusinessesBusinessIdPriceQuarantineConfirm
./api_dbs.go:623:8: undefined: CampaignsCampaignIdPriceQuarantineConfirm
./api_dbs.go:623:8: too many errors
```

**Comment by vbauer** [comment]
@DeOne4eg Спасибо за информацию. Если правильно понимаю, то это известная проблема в генераторе для golang: https://github.com/OpenAPITools/openapi-generator/issues/741 При включении structPrefix=true и enumClassPrefix=true проблемы с redeclaration уходят

Но кажется это не единственная проблема генератора и возникает другой сбой:
```
./api_bids.go:30:8: undefined: BusinessesBusinessIdBids
./api_bids.go:237:8: undefined: CampaignsCampaignIdBids
./api_business_offer_mappings.go:30:8: undefined: BusinessesBusinessIdOfferMappingsDelete
./api_business_offer_mappings.go:224:8: undefined: BusinessesBusinessIdOfferMappings
./api_business_offer_mappings.go:431:8: undefined: BusinessesBusinessIdOfferMappingsSuggestions
./api_business_offer_mappings.go:637:8: undefined: BusinessesBusinessIdOfferMappingsUpdate
./api_dbs.go:33:8: undefined: CampaignsCampaignIdOrdersOrderIdCancellationAccept
./api_dbs.go:224:8: undefined: CampaignsCampaignIdHiddenOffers
./api_dbs.go:423:8: undefined: BusinessesBusinessIdPriceQuarantineConfirm
./api_dbs.go:623:8: undefined: CampaignsCampaignIdPriceQuarantineConfirm
./api_dbs.go:623:8: too many errors
```

**Comment by DeOne4eg** [comment]
@vbauer спасибо, действительно так проблема решается.

По поводу другой проблемы тоже ковырялся, оказалось что проблема в фигурных скобках в названиях файлов. Если их убрать, то все работает.

**Comment by DeOne4eg** [comment]
Создал [PR](https://github.com/yandex-market/yandex-market-partner-api/pull/2) с исправлением

**Comment by MarketLLC** [comment]
@DeOne4eg Спасибо за исследование и PR, должно быть уже поправлено в рамках https://github.com/yandex-market/yandex-market-partner-api/commit/47e5bdd4530b88d4a4d296660e6bdf4fc6dda8e2

Проверьте пожалуйста

**Comment by DeOne4eg** [comment]
@MarketLLC да, работает. Спасибо за оперативность!
