### ISSUE TITLE
Верните файл ReportFormat

### ISSUE THREAD

**Issue by trgtrg** [yandex-market/yandex-market-partner-api#3]
В [этом коммите](https://github.com/yandex-market/yandex-market-partner-api/commit/5c7eac6b622f701e007c9a60bd92722454e1cff2#diff-f88eea27917e06496d8ca88cd61ffb96fe55f422f94ee9d25e8d44b69ac7bcb8) удалили файл **openapi/components/parameters/ReportFormat.yaml**

Хотя в [документации](https://yandex.ru/dev/market/partner-api/doc/ru/reference/reports/generateGoodsRealizationReport) ссылка на него осталась. Более того, изменили формат с **FILE** на **CSV | XLS**

Пожалуйста, не делайте подобных обратно-несовместимых изменений и не забывайте проверять такие вещи. Стоило оставить FILE для совместимости, который ссылается на XLS и добавить к нему два новых типа. Удалить его через пару месяцев, после оповещения пользователей.

**Comment by degoz16** [comment]
Добрый день, извините, просчитались с тем, что этот параметр уже находится в использовании, enum FILE вернули, параметр тоже сейчас вернется.
Хотели пока скрыть новую функциональность и слепо рассчитывали, что не required enum с одним значением еще не используется. В будущем не будем допускать просачивания таких параметров раньше времени.
