### ISSUE TITLE
API яндекс маркета для пользователя.

### ISSUE THREAD

**Issue by ZababurinSergei** [yandex-market/yandex-market-partner-api#5]
Скажите пожалуйста.

Есть ли возможность сделать витрину на своем сайте с помошью апи ?

Я бы хотел со своего сайта делать покупки в определенных магазинах.

Но в апи я не вижу методов, что бы получить списки существующих магазинов.

**Comment by vbauer** [comment]
@ZababurinSergei Здравствуйте, список магазинов можно получить с помощью метода https://yandex.ru/dev/market/partner-api/doc/ru/reference/campaigns/getCampaigns

**Comment by ZababurinSergei** [comment]
Но это список своих магазинов.
![image](https://github.com/yandex-market/yandex-market-partner-api/assets/108979720/c6b0ad3a-e7be-4cfb-8dcf-02641f0d5c78)


А мне хотелось такой кейс реализовать.

У меня в приложении отображается пятерочка дикси и другие магазины.

У себя в приложении я их покупаю, не используя веб клиент яндекса.

**Comment by vbauer** [comment]
Список всех / чужих магазинов которые не относятся к пользователю под которым выписан OAuth токен получить нельзя
